# Generated by Django 5.2.6 on 2025-09-10 06:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_completed', models.BooleanField(default=False)),
                ('total_images_captured', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('session_mode', models.CharField(choices=[('live', 'Live Camera'), ('demo', 'Demo Upload')], default='live', max_length=10)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_captures', models.IntegerField(default=0)),
                ('failed_captures', models.IntegerField(default=0)),
                ('session_completed', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_sessions', to='main_app.student')),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='enrollment_images/')),
                ('prompt_index', models.IntegerField()),
                ('image_sequence', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('face_coordinates', models.JSONField()),
                ('brightness_score', models.FloatField()),
                ('blur_score', models.FloatField()),
                ('capture_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('capture_mode', models.CharField(choices=[('live', 'Live Camera'), ('demo', 'Demo Upload')], default='live', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_images', to='main_app.student')),
            ],
            options={
                'ordering': ['student', 'prompt_index', 'image_sequence'],
                'unique_together': {('student', 'prompt_index', 'image_sequence')},
            },
        ),
    ]
