# Generated by Django 5.2.6 on 2025-09-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentimage',
            options={'ordering': ['student', 'prompt_index', 'capture_timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentimage',
            unique_together=set(),
        ),
    ]
