# Generated by Django 5.2.6 on 2025-09-10 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_enrollmentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('recognition_threshold', models.FloatField(default=0.6)),
                ('auto_mark_attendance', models.BooleanField(default=True)),
                ('total_recognitions', models.IntegerField(default=0)),
                ('unique_students_detected', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_time', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField()),
                ('recognition_successful', models.BooleanField()),
                ('image_quality_score', models.FloatField(blank=True, null=True)),
                ('face_size', models.CharField(blank=True, max_length=20)),
                ('lighting_conditions', models.CharField(blank=True, max_length=50)),
                ('attendance_marked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to='main_app.attendancesession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
            options={
                'ordering': ['-recognition_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('recognition_confidence', models.FloatField(default=0.0)),
                ('recognition_method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual', 'Manual Entry'), ('card', 'ID Card')], default='face_recognition', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=20)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='main_app.student')),
            ],
            options={
                'ordering': ['-date', '-entry_time'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_vector', models.JSONField()),
                ('encoding_quality', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='main_app.enrollmentimage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='main_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'enrollment_image')},
            },
        ),
    ]
