# Generated by Django 5.2.6 on 2025-09-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_attendancesession_recognitionlog_attendancerecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique setting key", max_length=100, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable setting name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this setting controls"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="General",
                        help_text="Setting category for grouping",
                        max_length=50,
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("STRING", "String"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Setting value (stored as text, converted by type)"
                    ),
                ),
                (
                    "default_value",
                    models.TextField(help_text="Default value for this setting"),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum value (for numeric types)",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum value (for numeric types)",
                        null=True,
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Regex for value validation",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_restart",
                    models.BooleanField(
                        default=False,
                        help_text="Does changing this setting require a restart?",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("last_modified_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
                "ordering": ["category", "name"],
            },
        ),
    ]
